auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: xiaoqx blog
url: http://xiaoqx.github.io
feed: /atom.xml
author_info: <a href="http://xiaoqx.github.io/">XiaoQixue</a>
